global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # TappHA Backend Application
  - job_name: 'tappha-backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Kafka JMX Metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL Metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    scrape_timeout: 10s

  # InfluxDB Metrics
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Event Processing Metrics
  - job_name: 'event-processing'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/api/events/performance'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true 