package com.tappha.ai.dto;

import lombok.Data;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import java.time.LocalDateTime;
import java.util.Map;

/**
 * Automation Suggestion DTO
 * 
 * Represents a single automation suggestion generated by AI
 * Following Agent OS Standards with safety and transparency
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AutomationSuggestion {

    /**
     * Unique suggestion ID
     */
    private String suggestionId;

    /**
     * Suggestion title/name
     */
    private String title;

    /**
     * Detailed description of the automation
     */
    private String description;

    /**
     * Confidence score (0.0 to 1.0)
     */
    private Double confidenceScore;

    /**
     * Safety score (0.0 to 1.0)
     */
    private Double safetyScore;

    /**
     * AI model used for this suggestion
     */
    private String modelUsed;

    /**
     * Reasoning and explanation for the suggestion
     */
    private String reasoning;

    /**
     * Suggested automation configuration
     */
    private Map<String, Object> automationConfig;

    /**
     * Devices involved in the automation
     */
    private String[] involvedDevices;

    /**
     * Estimated time savings (in minutes per day)
     */
    private Integer estimatedTimeSavings;

    /**
     * Energy efficiency impact
     */
    private String energyImpact;

    /**
     * User approval status
     */
    private String approvalStatus;

    /**
     * Timestamp when suggestion was generated
     */
    private LocalDateTime generatedAt;

    /**
     * Privacy level used (local-only, hybrid, cloud-augmented)
     */
    private String privacyLevel;

    /**
     * Additional metadata
     */
    private Map<String, Object> metadata;
} 